version: '3.3'

volumes:
  nextcloud:
  nextcloud-db:
  
services:
  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    restart: unless-stopped
    environment:
        TRUSTED_PROXIES: 172.19.0.4/16
        #OVERWRITEPROTOCOL: https
        OVERWRITECLIURL: https://nc.ilv.local
        OVERWRITEHOST: nc.ilv.local
        #REDIS_HOST: nextcloud-redis
        #REDIS_HOST_PASSWORD: test # Redis Passwort von oben wieder eingeben
    volumes:
      - nextcloud:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - "traefik.http.routers.nextcloud.rule=(Host(`nc.ilv.local`))"
      - "traefik.http.routers.nextcloud.tls=true"

    networks:
      - proxy
      - default
networks:
  proxy:
    name: traefik_proxy
    external: true
