version: '3'

volumes:
  nextcloud:
  nextcloud-db:

services:
  nc-db:
    image: mariadb:10.5
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=QwErT
      - MYSQL_PASSWORD=QwErT
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - proxy


  app:
    image: nextcloud
    container_name: nextcloud-app
    restart: unless-stopped
    #ports:
    #  - 8980:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=QwErT
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.service1-secure.entrypoints=https"
      - "traefik.http.routers.service1-secure.rule=Host(`nc.ilv.local`)"
      - "traefik.http.routers.service1-secure.tls=true"



networks:
  proxy:
    name: traefik_proxy
    external: true
