version: '3'

services:
  service2:
    image: containous/whoami
    container_name: service2
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
#      - "traefik.http.routers.service2.rule=Host(`service2.ilv.local`)"
#      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
#      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
#      - "traefik.http.routers.service2.middlewares=authelia@docker"
      - "traefik.http.routers.service2-secure.entrypoints=https"
      - "traefik.http.routers.service2-secure.rule=Host(`service2.ilv.local`)"
#      - "traefik.http.routers.service2-secure.middlewares=authelia@docker"
      - "traefik.http.routers.service2-secure.tls=true"
#      - "traefik.http.routers.service2-secure.service=api@internal"
networks:
  proxy:
    name: traefik_proxy

    external: true

